version: '3.1'

services:
  minio:
    restart: always
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    command: minio server /data --console-address ":9001"
  runner:
    image: ubuntu:latest
    command: mkdir -p /data/my-bucket
    depends_on:
      - minio
volumes:
  minio:
